name: re-run
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@21353adc5dabdc4178019aeb1fbe44e3f1db19e3
      - name: cat readme
        run: cat README.md  