name: re-run
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: Danithub/github-actions@7d73acd7490e568cb7753b479d0fed1275fd00a7
      - name: cat readme
        uses: cat README.md  