name: re-run
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/dev@9b3120c527d691747c9ce078b3084e12ca3a43a8
      - name: cat readme
        uses: cat README.md  